server:
  port: 9411
spring:
  application:
    name: hzh-zipkin
  main:
    allow-bean-definition-overriding: true

  boot:
    admin:
      client:
        #api-path:
        url: 127.0.0.1:8762
        #username:
        #connect-timeout: 5000ms
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    health-check-url: /health
    status-page-url: /info
    #
management:
  metrics:
    web:
      server:
        auto-time-requests: false
