server:
  port: 9000
spring:
  application:
    name: hzh-server-user
#  main:
#    allow-bean-definition-override : true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/systemapp?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
    druid:
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=${jxlife.publicKey}
      filters: stat,wall,slf4j,config
      initialSize: 1
      maxActive: 80
      maxPoolPreparedStatementPerConnectionSize: 20
      maxWait: 10000
      minEvictableIdleTimeMillis: 300000
      minIdle: 3
      poolPreparedStatements: true
      testOnBorrow: true
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 600000
      useGlobalDataSourceStat: true
      validationQuery: select 1
  zipkin:
    base-url: http://127.0.0.1:9411
    enabled: true
    sender:
      type: web
      #默认percentage: 0.1
    sleuth:
      sampler:
        percentage: 0.2

  boot:
    admin:
      client:
        #api-path:
        url: 127.0.0.1:8762
        #username:
        #connect-timeout: 5000ms


  redis:
        # Redis服务器地址
    host: 127.0.0.1
        # Redis服务器连接端口
    port: 6379
        # Redis服务器连接密码（默认为空）
    password:
        # 连接池最大连接数（使用负值表示没有限制）
      jedis:
        pool:
          max-active: 100
          max-idle: 10 # 连接池中的最大空闲连接
          max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
          min-idle: 0  # 连接池中的最小空闲连接
            # 连接超时时间（毫秒）
          timeout: 3000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    health-check-url: /health
    status-page-url: /info

mybatis:
  typeAliasesPackage: com.huang.server.service.vo
  mapperLocations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.huang.log.mapper: info