server:
  port: 8762
spring:
  application:
    name: hzh-admin

  zipkin:
    base-url: http://127.0.0.1:9411
    enabled: true
    sender:
      type: web
      #默认percentage: 0.1
    sleuth:
      sampler:
        percentage: 0.2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/


#监控配置，开启监控中心 springboot2.0 必要操作 * 表示监控所有信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

